package Entidades;

public enum Generos {
	ROCK, POP, JAZZ, HIP_HOP, CLASSICA, ELETRONICA, BLUES, REGGAE, FUNK, SOUL, SAMBA, BOSSA_NOVA, METAL, COUNTRY, FOLK,
	RAP, GOSPEL, LATINO, REGGAETON, MPB, INDIE, PUNK, R_AND_B, DISCO;
}
